/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(aggr_and_mux_vff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c0cc578d7a0d0dd78e5a2a12f9c7d884)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aggmux/aggr_and_mux_vff.h>
// pydoc.h is automatically generated in the build directory
#include <aggr_and_mux_vff_pydoc.h>

void bind_aggr_and_mux_vff(py::module& m)
{

    using aggr_and_mux_vff    = gr::aggmux::aggr_and_mux_vff;


    py::class_<aggr_and_mux_vff, gr::block, gr::basic_block,
        std::shared_ptr<aggr_and_mux_vff>>(m, "aggr_and_mux_vff", D(aggr_and_mux_vff))

        .def(py::init(&aggr_and_mux_vff::make),
           D(aggr_and_mux_vff,make)
        )
        



        ;




}








