/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hold_rewrite_tags_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(56b5c323bdcea6fd2c8a538a9b11e22c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aggmux/hold_rewrite_tags_cc.h>
// pydoc.h is automatically generated in the build directory
#include <hold_rewrite_tags_cc_pydoc.h>

void bind_hold_rewrite_tags_cc(py::module& m)
{

    using hold_rewrite_tags_cc = ::gr::aggmux::hold_rewrite_tags_cc;


    py::class_<hold_rewrite_tags_cc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<hold_rewrite_tags_cc>>(
        m, "hold_rewrite_tags_cc", D(hold_rewrite_tags_cc))

        .def(py::init(&hold_rewrite_tags_cc::make),
             py::arg("debug"),
             py::arg("sid"),
             D(hold_rewrite_tags_cc, make))


        ;
}
