/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(overlapping_stream_to_vec_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b5a0948cc8e95bfdbdc7497b962c5b42)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aggmux/overlapping_stream_to_vec_cc.h>
// pydoc.h is automatically generated in the build directory
#include <overlapping_stream_to_vec_cc_pydoc.h>

void bind_overlapping_stream_to_vec_cc(py::module& m)
{

    using overlapping_stream_to_vec_cc    = gr::aggmux::overlapping_stream_to_vec_cc;


    py::class_<overlapping_stream_to_vec_cc, gr::block, gr::basic_block,
        std::shared_ptr<overlapping_stream_to_vec_cc>>(m, "overlapping_stream_to_vec_cc", D(overlapping_stream_to_vec_cc))

        .def(py::init(&overlapping_stream_to_vec_cc::make),
           D(overlapping_stream_to_vec_cc,make)
        )
        



        ;




}








