/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(signalhound_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d2637feb56e08e52ca42936b00d7fcf9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/aggmux/signalhound_source.h>
// pydoc.h is automatically generated in the build directory
#include <signalhound_source_pydoc.h>

void bind_signalhound_source(py::module& m)
{

    using signalhound_source = ::gr::aggmux::signalhound_source;


    py::class_<signalhound_source,
               gr::block,
               gr::basic_block,
               std::shared_ptr<signalhound_source>>(
        m, "signalhound_source", D(signalhound_source))

        .def(py::init(&signalhound_source::make),
             py::arg("address") = "tcp://0.0.0.0:51665",
             py::arg("fft_bins") = 1024,
             py::arg("modalities") = 7,
             py::arg("max_update_freq") = 15,
             py::arg("debug") = false,
             D(signalhound_source, make))


        ;
}
